Spanish and Japanese translations for reports
archivesspace/archivesspace pull request #1995
Opened 2020-10-09 00:32 UTC by cdibella

## Description

Most of the out-of-the-box reports did not have Spanish or Japanese locales/translations. I added these and made a few other small locale-related fixes.

## Related JIRA Ticket or GitHub Issue

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-09 20:58 UTC, lorawoodford requested changes
Heya @cdibella - There are just 4 places where the first line is identifying English, instead of Spanish/Japanese.  After those are fixed these look good to go!

2020-10-09 20:58 UTC, lorawoodford commented on reports/accessions/accession_classifications_subreport/es.yml
> +en:
```suggestion
es:
```

2020-10-09 20:58 UTC, lorawoodford commented on reports/accessions/accession_classifications_subreport/ja.yml
> +en:
```suggestion
ja:
```

2020-10-09 20:58 UTC, lorawoodford commented on reports/accessions/accession_deaccessions_subreport/es.yml
> +en:
```suggestion
es:
```

2020-10-09 20:58 UTC, lorawoodford commented on reports/resources/resource_locations_list_report/es.yml
> +en:
```suggestion
es:
```

2020-10-09 21:17 UTC, cdibella commented
Ignore that mess I just put in that commit! Actual fix for this pending.

2020-10-12 14:26 UTC, lorawoodford approved these changes

2020-10-12 14:27 UTC, merged