ANW-97: Inactive users
archivesspace/archivesspace pull request #2318
Opened 2021-06-22 23:02 UTC by avatar382

## Description
Allows users to be marked inactive

## Related JIRA Ticket or GitHub Issue
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-97

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-09 18:45 UTC, quoideneuf commented on backend/app/controllers/users.rb
> +      handle_listing(User, params, {:exclude => {:id => User.unlisted_user_ids, :is_active_user => 0}})
```suggestion
      handle_listing(User, params, {:exclude => {:id => User.unlisted_user_ids}, :is_active_user => 1})
```
I think sending two keys to exclude will only exclude records matching both conditions, so you have to stick to one exclude field (or modify crud_helpers to support exclude chaining) and use a filter for `:is_active_user`

2021-07-09 18:48 UTC, quoideneuf commented on frontend/app/controllers/users_controller.rb
> +    show_inactive = params[:show_inactive] || false
what is this line doing? it doesn't appear that `show_inactive` is used.

2021-07-09 18:50 UTC, quoideneuf requested changes
It looks like the `show_inactive` param in both controllers is not doing anything. Maybe it can just be removed?

2021-07-14 18:34 UTC, avatar382 commented
> It looks like the `show_inactive` param in both controllers is not doing anything. Maybe it can just be removed?

Good catch, since all the users is shown in one view, you're right -- no need for the param. I've removed it from both controllers.

2021-07-19 14:37 UTC, quoideneuf approved these changes

2021-07-19 14:37 UTC, merged