ANW-1521: support for tooltips in subrecord header buttons
archivesspace/archivesspace pull request #2677
Opened 2022-03-31 15:43 UTC by avatar382

## Description
Adds tooltips to action buttons at the top of some subrecords in ASpace frontend forms to aid in adding user documentation

## Related JIRA Ticket or GitHub Issue
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1521

## How Has This Been Tested?
manual in browser testing

## Screenshots (if appropriate):
![Screenshot_2022-03-31_09-39-55](https://user-images.githubusercontent.com/130926/161095342-8fd0701c-b69f-4d7b-b93a-407c145344ac.jpg)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-08-17 20:54 UTC, quoideneuf requested changes
Looks good but we need some text for the 3 tooltips. Example: 
<img width="221" alt="image" src="https://user-images.githubusercontent.com/1626547/185241029-952c3e3f-c430-4d09-b7ff-c6927c4d14ac.png">
We need text for: "Make Representative Tooltip"; "Make Authoritative Name Tooltip"; "Make Display Name Tooltip"

2022-09-01 17:24 UTC, avatar382 commented
@cdibella Could you add the values needed here?

2022-09-01 17:45 UTC, cdibella commented
Make Representative Tooltip: Use to indicate that this image should be displayed when there are multiple file versions associated with the record.

Make Authoritative Name Tooltip: Use to indicate the name form is the authoritative version of the name.

Make Display Name Tooltip: Use to indicate that this form of the name should be used for displays when there are multiple name forms associated with the agent record.

2022-11-22 13:25 UTC, quoideneuf approved these changes

2022-11-22 13:25 UTC, merged