ANW-1260: MARCXML import: update 300 processing for extents
archivesspace/archivesspace pull request #2805
Opened 2022-09-08 15:19 UTC by avatar382

## Description
Improve processing of MARCXML 300 field extent processing

## Related JIRA Ticket or GitHub Issue
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1260

## How Has This Been Tested?
manual and unit testing

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-11-21 21:29 UTC, donaldjosephsmith submitted a review, later dismissed

2022-11-28 15:26 UTC, donaldjosephsmith requested changes
@avatar382 - Any chance I could get your assistance tracking down why these tests are failing? There was a conflict during merge that I believe I resolved properly, but a few tests that were added in the other conflicting PR (#2852) are now failing. I'm not sure if I missed something in the merge or if it's a case of the tests being based on assumptions that are no longer valid after this change.

2022-12-01 00:49 UTC, avatar382 commented
@donaldjosephsmith Some of the MARC in example files in PR # 2852 is no longer valid in this PR, so I've updated those files so the tests added here will pass. Should be good to go now.

> @avatar382 - Any chance I could get your assistance tracking down why these tests are failing? There was a conflict during merge that I believe I resolved properly, but a few tests that were added in the other conflicting PR (#2852) are now failing. I'm not sure if I missed something in the merge or if it's a case of the tests being based on assumptions that are no longer valid after this change.

2022-12-01 01:32 UTC, donaldjosephsmith commented
> @donaldjosephsmith Some of the MARC in example files in PR # 2852 is no longer valid in this PR, so I've updated those files so the tests added here will pass. Should be good to go now.

Perfect, thanks! 👍🏻

2022-12-01 01:43 UTC, merged