ANW-1703: scope d.obj collection to published a.objs
archivesspace/archivesspace pull request #2949
Opened 2023-03-01 01:56 UTC by mark-cooper

## Description

The digital object "collection" property should only be added to from an archival object when that object is published.
This will prevent digital objects linked to unpublished archival objects from appearing in the Digital Materials list / total for a resource (aka the "collection") in the PUI.

## Related JIRA Ticket or GitHub Issue

https://archivesspace.atlassian.net/browse/ANW-1703

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-03-05 13:57 UTC, brianzelip reviewed
This works.

2023-03-05 18:35 UTC, quoideneuf requested changes

2023-03-05 18:35 UTC, quoideneuf commented on backend/spec/mixin_touch_records_spec.rb
> +    expect(digital_object_updated_mt).to be > digital_object_orig_mt
This appears to be supported by https://github.com/archivesspace/archivesspace/blob/master/backend/app/model/mixins/relationships.rb#L841, so maybe the changes to `backend/app/model/archival_object.rb` are not actually needed?

2023-03-07 13:35 UTC, quoideneuf approved these changes

2023-03-07 13:35 UTC, merged