ANW-2221: Add tests for the staff add-as-you-go javascript feature
archivesspace/archivesspace pull request #3421
Opened 2024-12-05 20:10 UTC by brianzelip

This PR is a follow up from #3397 which fixed a problem related to the add-as-you-go feature but did not include any tests in favor of getting out the v4 release candidate.

This PR adds tests for the add-as-you-go feature across all record types, which is (unnecessarily) assembled wholly in JavaScript instead of template markup, and was not tested before this PR.

2024-12-06 15:50 UTC, thimios requested changes
I think it would be nicer to use the rspec concept of [shared examples](https://rspec.info/features/3-12/rspec-core/example-groups/shared-examples/). We already have this pattern in the code:

https://github.com/archivesspace/archivesspace/blob/master/backend/spec/export_ead3_spec.rb#L417
https://github.com/archivesspace/archivesspace/blob/master/backend/spec/export_ead3_spec.rb#L1080

2024-12-06 20:23 UTC, brianzelip commented
@thimios Only 7 lines shorter using `shared_examples`, but great to have the much-more-granular testing context. Thanks for the pointer to shared examples!

2024-12-09 11:29 UTC, thimios requested changes

2024-12-09 11:29 UTC, thimios commented on frontend/spec/features/add_as_you_go_spec.rb
> +    shared_examples 'top-level non-Notes subforms' do |type, num_expected_subforms, num_expected_header_buttons|
The title of the `shared_examples` block should read well when used in an `it_behaves_like` block, maybe something like: "a top level form without Notes subforms" ?

2024-12-09 11:29 UTC, thimios commented on frontend/spec/features/add_as_you_go_spec.rb
> +      it "for #{title}" do
I think we are missing a context (or maybe a describe?) block here that could be somethig like: `context "when creating #{title}"`.

The it block, should give a hint of what is actually being asserted here. Maybe something like: `it "contains add-as-you-go buttons"

2024-12-09 11:29 UTC, thimios commented on frontend/spec/features/add_as_you_go_spec.rb
> +  it 'are not present for Container Profiles' do
How about adding a `context` block and making the `it` block more descriptive, something like:
```
context "when creating Container Profiles" do
  it "does not contain notes subforms" do
    ...
```

2024-12-09 11:29 UTC, thimios commented on frontend/spec/features/add_as_you_go_spec.rb
> +    shared_examples 'top-level Notes subform' do |type|
same comment as above regarding naming shared_examples

2024-12-09 11:29 UTC, thimios commented on frontend/spec/features/add_as_you_go_spec.rb
> +      it "for #{type}s" do
same as above regarding naming examples

2024-12-09 18:37 UTC, thimios approved these changes

2024-12-09 18:37 UTC, merged