Use AppConfig for rails force_ssl to secure cookies etc.
archivesspace/archivesspace pull request #3430
Opened 2024-12-19 19:09 UTC by mark-cooper

Applies to Rails production env.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have authority to submit this code.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-12-19 19:09 UTC, mark-cooper commented
@thimios this is less well tested than #3429 but it has been deployed to a single site for testing and looks good. Compared with #3429 it leans on Rails cfg rather than inlining and it does addtl. security things as well (which can be done at other layers but this opts-in to secure defaults). Also running it through AppConfig allows it to be turned off (`AppConfig[:force_ssl] = false`) if that's useful (running in "prod" mode locally over http could be one use case).

2024-12-20 11:40 UTC, thimios commented
@mark-cooper looks good, could you make sure that the frontend specs also pass before merging?

2024-12-21 03:27 UTC, mark-cooper commented
@thimios wasn't an expecting an issue. I'll take a look soon!

2024-12-21 10:28 UTC, thimios commented
@mark-cooper another issue is that there are cases where the app needs to run on :production without requiring ssl, for example, in the e2d testing project, the app is running on docker: https://github.com/archivesspace/e2e-tests/blob/master/docker-compose.yml without https.

It was changed from running on the latest docker image to running on v4: https://github.com/archivesspace/e2e-tests/commit/0f4bac639236c85dcb9a38f88ac9d453a548ac27 because after merging the previous changes the login breaks.

Could we use an environment variable that we could set in the `docker-compose.yml` file to control whether using ssl is required or not?

2024-12-26 11:51 UTC, thimios commented
@mark-cooper it is indeed an unconventional way that we are using the Rails environment... Setting the default to false is definitely backwards compatible. 

I wonder how setting the `APPCONFIG_FORCE_SSL` environment variable is working, as I do not see any such string mentioned in the code. Is there a mechanism that allows overriding any setting with an env variable? 

In any case, could we add a comment in [config-defaults.rb](https://github.com/archivesspace/archivesspace/pull/3430/files#diff-dc23bbfe0e815823aff39052c243dbf2dbbf8d9d13a4065fda7a1e9b9d695ca2R106) to document that it is possible to override this setting using the `APPCONFIG_FORCE_SSL` variable?

2024-12-26 11:51 UTC, thimios requested changes

2025-01-07 02:04 UTC, mark-cooper commented
@thimios sorry, missed the question. Overriding config from ENV is defined in `config-distribution`: https://github.com/archivesspace/archivesspace/blob/master/common/config/config-distribution.rb#L93-L102

Do you still want to mention the override in the config file considering there's a general mechanism for overriding any config through the environment? (well, I think it's somewhat limited and can't do `procs` and maybe some other things)

2025-01-07 11:37 UTC, thimios commented
@mark-cooper great that this mechanism exists. I think it does not make sense to mention the override in the config file for this specific setting, but I do wonder if this generic mechanism of overriding settings through env vars is documented. 

Adding this generic documentation (if you also think is needed) should not be part of this PR, but I think we should document this mechanism in tech-docs and in a comment at the top of the config file. Let me know if you agree and I will take care of adding that documentation.

2025-01-07 11:37 UTC, thimios approved these changes

2025-01-07 11:45 UTC, merged